// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjSRMmkk8zdeXOUCFl5V2UlKXK9piHhvo',
    appId: '1:248757396448:web:c4bc3fd478f65c92a3c185',
    messagingSenderId: '248757396448',
    projectId: 'fir-9769b',
    authDomain: 'fir-9769b.firebaseapp.com',
    storageBucket: 'fir-9769b.firebasestorage.app',
    measurementId: 'G-T3WV63TYRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU7i7bbYPuA7rOWjG3G8iDjlFG1r0TxN8',
    appId: '1:248757396448:android:d28cf70d947931b6a3c185',
    messagingSenderId: '248757396448',
    projectId: 'fir-9769b',
    storageBucket: 'fir-9769b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzlSjBkJyNo_mteTjQpfO5MmOFHpFt0Y8',
    appId: '1:248757396448:ios:15d32bc0dd361686a3c185',
    messagingSenderId: '248757396448',
    projectId: 'fir-9769b',
    storageBucket: 'fir-9769b.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzlSjBkJyNo_mteTjQpfO5MmOFHpFt0Y8',
    appId: '1:248757396448:ios:15d32bc0dd361686a3c185',
    messagingSenderId: '248757396448',
    projectId: 'fir-9769b',
    storageBucket: 'fir-9769b.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjSRMmkk8zdeXOUCFl5V2UlKXK9piHhvo',
    appId: '1:248757396448:web:35ba2820b0ac524aa3c185',
    messagingSenderId: '248757396448',
    projectId: 'fir-9769b',
    authDomain: 'fir-9769b.firebaseapp.com',
    storageBucket: 'fir-9769b.firebasestorage.app',
    measurementId: 'G-GNCHDD3JYG',
  );
}
